name: Build for Linux amr46

on:
  push:  
    # Sequence of patterns matched against refs/tags
    tags:        
      - '**'

jobs:
  run_arm64:
    runs-on: self-hosted

    name: Build for arm64
    permissions:
      contents: write

    steps:

    - name: Clone repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        wget -q https://services.gradle.org/distributions/gradle-6.9-bin.zip
        unzip gradle-6.9-bin.zip

    - name: Clone
      run: |
        git clone https://github.com/makewise-vision/openvino_contrib -b releases/2023/3 --depth 1
        cd openvino_contrib && echo "https://github.com/makewise-vision/openvino_contrib/commit/$(git rev-parse HEAD)" >> ../versions.txt && cd ..

        git clone https://github.com/openvinotoolkit/testdata -b releases/2023/3 --depth 1
        cd testdata && git lfs pull

    - name: Upload versions.txt
      uses: actions/upload-artifact@v2
      with:
        name: "versions"
        path: "versions.txt"

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        architecture: 'aarch64'

    - name: Install OpenVINO
      run: |
        wget -q https://storage.openvinotoolkit.org/repositories/openvino/packages/2023.3/linux/l_openvino_toolkit_ubuntu18_2023.3.0.13775.ceeafaf64f3_arm64.tgz -O openvino.tgz
        sudo mkdir -p /opt/intel/openvino
        sudo tar -xf openvino.tgz -C /opt/intel/openvino --strip-components=1
        sudo /opt/intel/openvino/install_dependencies/install_openvino_dependencies.sh -y

    - name: Build bindings
      run: |
        mkdir build_api && cd build_api
        source /opt/intel/openvino/setupvars.sh
        cmake ../openvino_contrib/modules/java_api \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_FLAGS="-std=c++11"
        make -j$(nproc --all)
        sudo cp *.so /opt/intel/openvino/runtime/lib/aarch64

    - name: Build package
      run: |
        source /opt/intel/openvino/setupvars.sh
        ../../../gradle-6.9/bin/gradle clean build --info
        ../../../gradle-6.9/bin/gradle test -Prun_tests -DMODELS_PATH=../../../testdata -Ddevice=CPU --info
      working-directory: openvino_contrib/modules/java_api

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: "pkg_lnx"
        path: "openvino_contrib/modules/java_api/build/libs/*.jar"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          openvino_contrib/modules/java_api/build/libs/openvino-2023.3-linux-arm64.jar
