name: Build for Linux

on:
  push:  
    # Sequence of patterns matched against refs/tags
    tags:        
      - '**'

jobs:
  run_linux:
    runs-on: ubuntu-20.04
    name: Build on Linux

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        wget -q https://downloads.gradle-dn.com/distributions/gradle-6.2.2-bin.zip
        unzip gradle-6.2.2-bin.zip

    - name: Clone
      run: |
        git clone https://github.com/openvinotoolkit/openvino_contrib -b releases/2023/0 --depth 1
        cd openvino_contrib && echo "https://github.com/openvinotoolkit/openvino_contrib/commit/$(git rev-parse HEAD)" >> ../versions.txt && cd ..

        git clone https://github.com/openvinotoolkit/testdata -b releases/2023/0 --depth 1
        cd testdata && git lfs pull

    - name: Upload versions.txt
      uses: actions/upload-artifact@v2
      with:
        name: "versions"
        path: "versions.txt"

    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.2'

    - name: Install OpenVINO
      run: |
        wget -q https://storage.openvinotoolkit.org/repositories/openvino/packages/2023.0/linux/l_openvino_toolkit_rhel8_2023.0.0.10926.b4452d56304_x86_64.tgz -O openvino.tgz
        sudo mkdir -p /opt/intel/openvino
        sudo tar -xf openvino.tgz -C /opt/intel/openvino --strip-components=1
        sudo apt-get install -y libtbb2 libpugixml1v5

    - name: Build bindings
      run: |
        mkdir build_api && cd build_api
        source /opt/intel/openvino/setupvars.sh
        cmake ../openvino_contrib/modules/java_api \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_FLAGS="-std=c++11"
        make -j$(nproc --all)
        sudo cp *.so /opt/intel/openvino/runtime/lib/intel64

    - name: Build package
      run: |
        source /opt/intel/openvino/setupvars.sh
        ../../../gradle-6.2.2/bin/gradle clean build --info
        ../../../gradle-6.2.2/bin/gradle test -Prun_tests -DMODELS_PATH=../../../testdata -Ddevice=CPU --info
      working-directory: openvino_contrib/modules/java_api

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: "pkg_lnx"
        path: "openvino_contrib/modules/java_api/build/libs/*.jar"
